### ISSUE TITLE
[16.0] account_invoice_overdue_reminder

### ISSUE THREAD

**Issue by ThijsvOers** [OCA/credit-control#331]
After sending the first reminder, it is possible to manually add lines on the tab 'overdue reminder'. When I add a line fill in the reason and note I get an error on saving the record

![error](https://github.com/OCA/credit-control/assets/30256071/1e6089e5-cd6a-48eb-b2bd-c73b1636cd5c)

## Module
 account_invoice_overdue_reminder

Error:
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/odoo/src/odoo/odoo/http.py", line 1583, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/odoo/src/odoo/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/odoo/src/odoo/odoo/http.py", line 1610, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/odoo/src/odoo/odoo/http.py", line 1807, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/odoo/src/odoo/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/odoo/src/odoo/odoo/http.py", line 696, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/odoo/src/odoo/addons/web/controllers/dataset.py", line 42, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/src/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/src/odoo/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo/src/odoo/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/src/odoo/addons/account/models/account_move.py", line 2336, in onchange
    return super().onchange(values, field_name, field_onchange)
  File "/odoo/src/odoo/odoo/models.py", line 6513, in onchange
    todo = [
  File "/odoo/src/odoo/odoo/models.py", line 6516, in <listcomp>
    if name not in done and snapshot0.has_changed(name)
  File "/odoo/src/odoo/odoo/models.py", line 6299, in has_changed
    return self[name] != record[name]
  File "/odoo/src/odoo/odoo/models.py", line 5858, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/odoo/src/odoo/odoo/fields.py", line 1157, in __get__
    self.recompute(record)
  File "/odoo/src/odoo/odoo/fields.py", line 1345, in recompute
    self.compute_value(recs)
  File "/odoo/src/odoo/odoo/fields.py", line 1367, in compute_value
    records._compute_field_value(self)
  File "/odoo/src/odoo/addons/mail/models/mail_thread.py", line 403, in _compute_field_value
    return super()._compute_field_value(field)
  File "/odoo/src/odoo/odoo/models.py", line 4193, in _compute_field_value
    fields.determine(field.compute, self)
  File "/odoo/src/odoo/odoo/fields.py", line 97, in determine
    return needle(*args)
  File "/odoo/custom/account_invoice_overdue_reminder/models/account_move.py", line 70, in _compute_overdue_reminder
    move.overdue_reminder_last_date = all_dates and max(all_dates) or False
TypeError: '>' not supported between instances of 'bool' and 'datetime.date'

The above server error caused the following client error:
null

**Comment by ThijsvOers** [comment]
Solved in #332 and tested by me, I will close this task
